"""
pyrit_mcp.utils.system_detect — Hardware detection and model recommendation.

Wraps the ``.env.detected`` file (generated by ``make detect`` on Linux) to
expose hardware detection data to MCP tools at runtime.  Also reads
``config/tier_profiles.json`` and ``config/model_catalog.json`` to implement
tier-based model recommendation logic.

On Windows or when no detection has been run, all functions degrade gracefully
and return sensible defaults so that the rest of the server can still operate.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

_PROJECT_ROOT = Path(__file__).resolve().parents[2]  # pyrit_mcp/utils -> repo root
_ENV_DETECTED_PATH = _PROJECT_ROOT / ".env.detected"
_TIER_PROFILES_PATH = _PROJECT_ROOT / "config" / "tier_profiles.json"
_MODEL_CATALOG_PATH = _PROJECT_ROOT / "config" / "model_catalog.json"

# ---------------------------------------------------------------------------
# Internal loaders
# ---------------------------------------------------------------------------


def _parse_env_detected(path: Path | None = None) -> dict[str, str]:
    """Parse a ``.env.detected`` file into a flat ``{KEY: value}`` dict.

    Lines that are blank, start with ``#``, or lack an ``=`` are silently
    skipped.  Values surrounded by double-quotes are unquoted.

    Returns an empty dict if the file does not exist.
    """
    target = path or _ENV_DETECTED_PATH
    if not target.is_file():
        logger.info(
            ".env.detected not found at %s — hardware detection data unavailable",
            target,
        )
        return {}

    result: dict[str, str] = {}
    try:
        for raw_line in target.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            # Strip optional surrounding double-quotes
            if len(value) >= 2 and value.startswith('"') and value.endswith('"'):
                value = value[1:-1]
            result[key] = value
    except OSError as exc:
        logger.warning("Failed to read %s: %s", target, exc)
    return result


def _load_json(path: Path) -> dict[str, Any]:
    """Load a JSON config file.  Returns ``{}`` on any error."""
    if not path.is_file():
        logger.warning("Config file not found: %s", path)
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Failed to load %s: %s", path, exc)
        return {}


def _load_tier_profiles() -> list[dict[str, Any]]:
    """Return the ``tiers`` list from ``tier_profiles.json``."""
    data = _load_json(_TIER_PROFILES_PATH)
    tiers: list[dict[str, Any]] = data.get("tiers", [])
    return tiers


def _load_model_catalog() -> dict[str, dict[str, Any]]:
    """Return a ``{model_id: model_entry}`` mapping from ``model_catalog.json``."""
    data = _load_json(_MODEL_CATALOG_PATH)
    models: list[dict[str, Any]] = data.get("models", [])
    return {m["id"]: m for m in models if "id" in m}


# ---------------------------------------------------------------------------
# Cached data (loaded on first access)
# ---------------------------------------------------------------------------

_tier_profiles_cache: list[dict[str, Any]] | None = None
_model_catalog_cache: dict[str, dict[str, Any]] | None = None


def _get_tiers() -> list[dict[str, Any]]:
    global _tier_profiles_cache
    if _tier_profiles_cache is None:
        _tier_profiles_cache = _load_tier_profiles()
    return _tier_profiles_cache


def _get_catalog() -> dict[str, dict[str, Any]]:
    global _model_catalog_cache
    if _model_catalog_cache is None:
        _model_catalog_cache = _load_model_catalog()
    return _model_catalog_cache


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def _to_float(value: str, default: float = 0.0) -> float:
    """Best-effort conversion to float."""
    try:
        return float(value)
    except (ValueError, TypeError):
        return default


def _to_int(value: str, default: int = 0) -> int:
    """Best-effort conversion to int."""
    try:
        return int(value)
    except (ValueError, TypeError):
        return default


def _to_bool(value: str) -> bool:
    """Convert shell-style boolean to Python bool."""
    return value.strip().lower() in ("true", "1", "yes")


def load_tier_profiles() -> list[dict[str, Any]]:
    """Load and return the tier profiles from ``config/tier_profiles.json``.

    Returns:
        List of tier dicts, each with tier_id, ram_min_gb, ram_max_gb, etc.
    """
    return list(_get_tiers())


def load_model_catalog() -> list[dict[str, Any]]:
    """Load and return the model catalog from ``config/model_catalog.json``.

    Returns:
        List of model dicts, each with id, family, params_b, quantizations, etc.
    """
    return list(_get_catalog().values())


def get_system_profile(env_path: Path | None = None) -> dict[str, Any]:
    """Return detected hardware info as a structured dict.

    If ``.env.detected`` does not exist (e.g. Windows dev environment or
    detection has not been run) the returned dict will have
    ``"detected": False`` and all hardware fields set to ``None``.

    Returns:
        A dict with the following shape::

            {
                "detected": bool,
                "total_ram_gb": float | None,
                "available_ram_gb": float | None,
                "cpu_cores": int | None,
                "cpu_model": str | None,
                "cpu_sockets": int | None,
                "numa_nodes": int | None,
                "has_nvidia_gpu": bool | None,
                "has_amd_gpu": bool | None,
                "gpu_vram_gb": float | None,
                "inference_mode": str | None,
                "recommended_compose_profile": str | None,
            }
    """
    env = _parse_env_detected(env_path)

    if not env:
        return {
            "detected": False,
            "total_ram_gb": None,
            "available_ram_gb": None,
            "cpu_cores": None,
            "cpu_model": None,
            "cpu_sockets": None,
            "numa_nodes": None,
            "has_nvidia_gpu": None,
            "has_amd_gpu": None,
            "gpu_vram_gb": None,
            "inference_mode": None,
            "recommended_compose_profile": None,
        }

    return {
        "detected": True,
        "total_ram_gb": _to_float(env.get("DETECTED_TOTAL_RAM_GB", "")),
        "available_ram_gb": _to_float(env.get("DETECTED_AVAILABLE_RAM_GB", "")),
        "cpu_cores": _to_int(env.get("DETECTED_CPU_CORES", "")),
        "cpu_model": env.get("DETECTED_CPU_MODEL"),
        "cpu_sockets": _to_int(env.get("DETECTED_CPU_SOCKETS", "")),
        "numa_nodes": _to_int(env.get("DETECTED_NUMA_NODES", "")),
        "has_nvidia_gpu": _to_bool(env.get("DETECTED_HAS_NVIDIA_GPU", "false")),
        "has_amd_gpu": _to_bool(env.get("DETECTED_HAS_AMD_GPU", "false")),
        "gpu_vram_gb": _to_float(env.get("DETECTED_GPU_VRAM_GB", "")),
        "inference_mode": env.get("DETECTED_INFERENCE_MODE"),
        "recommended_compose_profile": env.get("RECOMMENDED_COMPOSE_PROFILE"),
    }


def _enrich_model(role_config: dict[str, Any]) -> dict[str, Any]:
    """Merge tier role config with full model details from the catalog.

    Returns a new dict containing the tier config overlaid with catalog info
    (family, params_b, quantization details, notes, etc.) when available.
    """
    catalog = _get_catalog()
    model_id: str | None = role_config.get("model_id")
    if not model_id or model_id not in catalog:
        return dict(role_config)

    entry = catalog[model_id]
    quant_id = role_config.get("quant_id")

    enriched: dict[str, Any] = dict(role_config)
    enriched["family"] = entry.get("family")
    enriched["params_b"] = entry.get("params_b")
    enriched["uncensored"] = entry.get("uncensored")
    enriched["ollama_name"] = entry.get("ollama_name")
    enriched["hf_repo"] = entry.get("hf_repo")
    enriched["model_notes"] = entry.get("notes")

    # Attach the specific quantization detail if we can find it
    if quant_id:
        for q in entry.get("quantizations", []):
            if q.get("quant_id") == quant_id:
                enriched["quant_detail"] = q
                break

    return enriched


def recommend_models(
    available_ram_gb: float,
    has_gpu: bool = False,
    gpu_vram_gb: float = 0.0,
    role: str = "both",
) -> dict[str, Any]:
    """Return model recommendations for the given hardware profile.

    Matches ``available_ram_gb`` against tiers defined in
    ``config/tier_profiles.json`` and enriches the result with model details
    from ``config/model_catalog.json``.

    Args:
        available_ram_gb: Usable RAM in gigabytes.
        has_gpu: Whether a supported GPU is present.
        gpu_vram_gb: GPU VRAM in gigabytes (0 if no GPU).
        role: Filter recommendations — ``"attacker"``, ``"scorer"``, or
              ``"both"`` / ``"all"`` (default).

    Returns:
        A structured dict::

            {
                "status": "success" | "no_match",
                "tier": { ... },
                "attacker": { ... },        # present when role is "attacker" or "all"
                "scorer": { ... },          # present when role is "scorer" or "all"
                "fallback_attacker": { ... } | None,
                "attacker_high_ram": { ... } | None,
                "gpu": { ... } | None,
                "capabilities": [...],
                "limitations": [...],
                "notes": str,
            }
    """
    tiers = _get_tiers()
    if not tiers:
        logger.warning("No tier profiles loaded — cannot recommend models")
        return {
            "status": "no_match",
            "reason": "tier_profiles.json not found or empty",
        }

    matched_tier: dict[str, Any] | None = None
    for tier in tiers:
        ram_min = tier.get("ram_min_gb", 0)
        ram_max = tier.get("ram_max_gb", 0)
        if ram_min <= available_ram_gb <= ram_max:
            matched_tier = tier
            break

    # If RAM exceeds the highest tier's max, use the highest tier
    if matched_tier is None and tiers:
        highest = max(tiers, key=lambda t: t.get("ram_max_gb", 0))
        if available_ram_gb > highest.get("ram_max_gb", 0):
            matched_tier = highest

    # If RAM is below the lowest tier's minimum, use Tier 1 (best effort)
    if matched_tier is None and tiers:
        lowest = min(tiers, key=lambda t: t.get("ram_min_gb", 0))
        matched_tier = lowest

    if matched_tier is None:
        return {
            "status": "no_match",
            "reason": "tier_profiles.json not found or empty",
        }

    # Build the result with top-level convenience fields
    tier_id = matched_tier.get("tier_id")
    compose_profile = matched_tier.get("compose_profile", "")
    attacker_ram = matched_tier.get("attacker", {}).get("ram_gb", 0)
    scorer_ram = matched_tier.get("scorer", {}).get("ram_gb", 0)
    total_ram_required = attacker_ram + scorer_ram

    result: dict[str, Any] = {
        "status": "success",
        "tier_id": tier_id,
        "label": matched_tier.get("label"),
        "compose_profile": compose_profile,
        "total_ram_required_gb": total_ram_required,
        "remaining_ram_gb": max(0, available_ram_gb - total_ram_required),
        "has_gpu": has_gpu,
        "gpu_vram_gb": gpu_vram_gb,
    }

    # Attacker
    if role in ("attacker", "all", "both") and "attacker" in matched_tier:
        result["attacker"] = _enrich_model(matched_tier["attacker"])

    # Scorer
    if role in ("scorer", "all", "both") and "scorer" in matched_tier:
        result["scorer"] = _enrich_model(matched_tier["scorer"])

    # Optional: high-RAM attacker variant
    high_ram = matched_tier.get("attacker_high_ram")
    if high_ram and role in ("attacker", "all", "both"):
        result["attacker_high_ram"] = _enrich_model(high_ram)
    else:
        result["attacker_high_ram"] = None

    # Optional: fallback attacker
    fallback = matched_tier.get("fallback_attacker")
    if fallback and role in ("attacker", "all", "both"):
        result["fallback_attacker"] = _enrich_model(fallback)
    else:
        result["fallback_attacker"] = None

    # GPU info
    if has_gpu and gpu_vram_gb > 0:
        result["gpu"] = {
            "has_gpu": True,
            "gpu_vram_gb": gpu_vram_gb,
            "note": (
                "GPU acceleration may improve inference speed. Check backend "
                "documentation for GPU offloading options."
            ),
        }
    else:
        result["gpu"] = None

    result["capabilities"] = matched_tier.get("capabilities", [])
    result["limitations"] = matched_tier.get("limitations", [])
    result["notes"] = matched_tier.get("notes", "")

    return result
